services:
  - type: web
    name: eklavya-coaching-center
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: ADMIN_USER
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
