const express=require("express"),fs=require("fs"),path=require("path"),crypto=require("crypto");
const app=express(),PORT=process.env.PORT||3000,dir=path.join(__dirname,"data"),file=path.join(dir,"site.json"),sessions=new Map();
const initial={notices:[{id:1,title:"Admissions & Enquiries",text:"Contact Eklavya Coaching Center for current batch and admission information.",date:"01 Sep 2026"}],results:[],materials:[],gallery:[]};
if(!fs.existsSync(dir))fs.mkdirSync(dir);if(!fs.existsSync(file))fs.writeFileSync(file,JSON.stringify(initial,null,2));
const read=()=>JSON.parse(fs.readFileSync(file,"utf8")),write=x=>fs.writeFileSync(file,JSON.stringify(x,null,2));
app.use(express.json({limit:"1mb"}));app.use(express.urlencoded({extended:true}));app.use(express.static(path.join(__dirname,"public")));
const USER=process.env.ADMIN_USER||"admin",PASS=process.env.ADMIN_PASSWORD||"change-this-password";
const auth=(req,res,next)=>{const t=(req.headers.authorization||"").replace(/^Bearer\s+/i,"");if(!sessions.has(t))return res.status(401).json({error:"Unauthorized"});next()};
app.get("/health",(q,s)=>s.json({ok:true,service:"eklavya-coaching-center",version:"6.0.0"}));app.get("/api/site",(q,s)=>s.json(read()));
app.post("/api/login",(q,s)=>{if(String(q.body.username||"")!==USER||String(q.body.password||"")!==PASS)return s.status(401).json({error:"Invalid username or password"});const t=crypto.randomBytes(32).toString("hex");sessions.set(t,Date.now());s.json({token:t})});
app.post("/api/logout",auth,(q,s)=>{sessions.delete(q.headers.authorization.replace(/^Bearer\s+/i,""));s.json({ok:true})});
app.get("/admin",(q,s)=>s.sendFile(path.join(__dirname,"public/admin.html")));app.get("/login.html",(q,s)=>s.sendFile(path.join(__dirname,"public/login.html")));
const add=(type,fields)=>(q,s)=>{let d=read(),x={id:Date.now()};fields.forEach(k=>x[k]=String(q.body[k]||"").trim());if(fields.some(k=>!x[k]))return s.status(400).json({error:"Required fields are missing."});d[type].unshift(x);write(d);s.status(201).json(x)};
const del=type=>(q,s)=>{let d=read();d[type]=d[type].filter(x=>String(x.id)!==q.params.id);write(d);s.json({ok:true})};
app.post("/api/notices",auth,add("notices",["title","text","date"]));app.delete("/api/notices/:id",auth,del("notices"));
app.post("/api/results",auth,add("results",["student","className","achievement","year"]));app.delete("/api/results/:id",auth,del("results"));
app.post("/api/materials",auth,add("materials",["title","subject","url"]));app.delete("/api/materials/:id",auth,del("materials"));
app.post("/api/gallery",auth,add("gallery",["title","imageUrl"]));app.delete("/api/gallery/:id",auth,del("gallery"));
app.listen(PORT,"0.0.0.0",()=>console.log("Eklavya V6 running on "+PORT));